from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
OUTPUT = ROOT / "docs-site" / "src" / "content" / "docs" / "reference" / "semantic-concepts.md"

if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from ausecon_mcp.catalogue.resolver import list_economic_concepts  # noqa: E402


def _cell(value: Any) -> str:
    if value is None or value == "":
        return "n/a"
    if isinstance(value, list):
        if not value:
            return "n/a"
        return ", ".join(str(item) for item in value)
    return str(value).replace("\n", " ").replace("|", "\\|")


def _render() -> str:
    rows = sorted(
        list_economic_concepts(),
        key=lambda row: (str(row["category"]), str(row["source"]), str(row["concept"])),
    )
    categories = sorted({str(row["category"]) for row in rows})

    lines = [
        "---",
        "title: Semantic Concepts",
        "description: Curated concepts accepted by get_economic_series.",
        "---",
        "",
        "<!-- Generated by scripts/update_docs_reference.py. Do not edit by hand. -->",
        "",
        "`get_economic_series` accepts the following curated concepts. Each row resolves to a",
        "source-native ABS or RBA target and can be discovered at runtime with",
        "`list_economic_concepts` or the `ausecon://concepts` resource.",
        "",
        f"Total concepts: `{len(rows)}`.",
        "",
    ]

    for category in categories:
        category_rows = [row for row in rows if row["category"] == category]
        lines.extend(
            [
                f"## {category.replace('_', ' ').title()}",
                "",
                "| Concept | Source | Dataset | Variant | Frequency | Recommended call |",
                "| --- | --- | --- | --- | --- | --- |",
            ]
        )
        for row in category_rows:
            call = f'`get_economic_series(concept="{row["concept"]}")`'
            lines.append(
                " | ".join(
                    [
                        f"`{_cell(row['concept'])}`",
                        _cell(row["source"]).upper(),
                        f"`{_cell(row['dataset_id'])}`",
                        f"`{_cell(row['variant'])}`",
                        _cell(row["frequency"]),
                        call,
                    ]
                ).join(("| ", " |"))
            )
        lines.append("")

    lines.extend(
        [
            "## Notes",
            "",
            "- Concept rows are generated from the runtime semantic resolver, not copied from",
            "  the README.",
            "- Use `variant`, `geography`, and `frequency` only where the concept entry declares",
            "  support for those selectors.",
            "- Source-native retrieval details remain available through `search_datasets`,",
            "  `list_catalogue`, `get_abs_dataset_structure`, `get_abs_data`, and",
            "  `get_rba_table` or `get_apra_data`.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate or verify the Starlight semantic-concepts reference page."
    )
    parser.add_argument("--check", action="store_true", help="Fail if the generated page is stale.")
    args = parser.parse_args()

    rendered = _render()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != rendered:
            print(
                f"{OUTPUT.relative_to(ROOT)} is stale. "
                "Run `uv run python scripts/update_docs_reference.py`."
            )
            return 1
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
