ABS_CATALOGUE = {
    "CPI": {
        "id": "CPI",
        "source": "abs",
        "name": "Consumer Price Index",
        "description": "Consumer prices, headline inflation, and underlying inflation measures.",
        "frequency": "Quarterly",
        "category": "prices_inflation",
        "aliases": [
            "cpi",
            "consumer price index",
            "headline inflation",
            "trimmed mean",
            "weighted median",
        ],
        "tags": [
            "inflation",
            "consumer prices",
            "prices",
            "headline cpi",
            "underlying inflation",
        ],
    },
    "MCPI": {
        "id": "MCPI",
        "source": "abs",
        "name": "Monthly Consumer Price Index Indicator",
        "description": (
            "Monthly CPI indicator with selected expenditure classes and annual inflation."
        ),
        "frequency": "Monthly",
        "category": "prices_inflation",
        "aliases": [
            "monthly cpi",
            "monthly cpi indicator",
            "monthly inflation",
        ],
        "tags": [
            "inflation nowcast",
            "monthly prices",
            "consumer prices",
        ],
    },
    "PPI": {
        "id": "PPI",
        "source": "abs",
        "name": "Producer Price Indexes",
        "description": "Producer, export, and import price indexes across major industries.",
        "frequency": "Quarterly",
        "category": "prices_inflation",
        "aliases": [
            "ppi",
            "producer price indexes",
            "producer prices",
        ],
        "tags": [
            "import prices",
            "export prices",
            "upstream inflation",
        ],
    },
    "WPI": {
        "id": "WPI",
        "source": "abs",
        "name": "Wage Price Index",
        "description": "Wage inflation across sectors and industries in Australia.",
        "frequency": "Quarterly",
        "category": "prices_inflation",
        "aliases": [
            "wpi",
            "wage price index",
            "wage inflation",
        ],
        "tags": [
            "wages",
            "labour costs",
            "earnings",
        ],
    },
    "LF": {
        "id": "LF",
        "source": "abs",
        "name": "Labour Force Survey",
        "description": "Employment, unemployment, participation, and labour market conditions.",
        "frequency": "Monthly",
        "category": "labour",
        "aliases": [
            "labour force",
            "labour force survey",
            "employment",
            "unemployment",
            "unemployment rate",
            "jobless rate",
        ],
        "tags": [
            "participation",
            "jobs",
            "labour market",
        ],
    },
    "JV": {
        "id": "JV",
        "source": "abs",
        "name": "Job Vacancies",
        "description": "Quarterly job vacancies across industries and states.",
        "frequency": "Quarterly",
        "category": "labour",
        "aliases": [
            "job vacancies",
            "vacancies",
            "hiring demand",
        ],
        "tags": [
            "labour demand",
            "recruitment",
            "vacant positions",
        ],
    },
    "NAQ": {
        "id": "NAQ",
        "source": "abs",
        "name": "Australian National Accounts: Quarterly",
        "description": "Quarterly national accounts including GDP and expenditure components.",
        "frequency": "Quarterly",
        "category": "national_accounts",
        "aliases": [
            "gdp",
            "gdp growth",
            "national accounts",
            "economic growth",
        ],
        "tags": [
            "output",
            "consumption",
            "investment",
            "quarterly growth",
        ],
    },
    "RT": {
        "id": "RT",
        "source": "abs",
        "name": "Retail Trade",
        "description": "Monthly turnover across Australian retail industries and states.",
        "frequency": "Monthly",
        "category": "activity",
        "aliases": [
            "retail trade",
            "retail sales",
            "retail turnover",
        ],
        "tags": [
            "consumer spending",
            "household demand",
            "shops",
        ],
    },
    "BIA": {
        "id": "BIA",
        "source": "abs",
        "name": "Business Indicators, Australia",
        "description": (
            "Company profits, inventories, and sales indicators for the business sector."
        ),
        "frequency": "Quarterly",
        "category": "activity",
        "aliases": [
            "business indicators",
            "company profits",
            "inventories",
        ],
        "tags": [
            "sales",
            "profits",
            "private sector activity",
        ],
    },
    "MHSI": {
        "id": "MHSI",
        "source": "abs",
        "name": "Monthly Household Spending Indicator",
        "description": "Card and household spending signals across major consumption groups.",
        "frequency": "Monthly",
        "category": "activity",
        "aliases": [
            "household spending",
            "monthly household spending indicator",
            "card spending",
        ],
        "tags": [
            "consumer activity",
            "payments",
            "discretionary spending",
        ],
    },
    "BA": {
        "id": "BA",
        "source": "abs",
        "name": "Building Approvals",
        "description": "Dwelling approvals and construction intentions by geography and type.",
        "frequency": "Monthly",
        "category": "housing_construction",
        "aliases": [
            "building approvals",
            "dwelling approvals",
            "housing approvals",
        ],
        "tags": [
            "construction pipeline",
            "residential approvals",
            "new dwellings",
        ],
    },
    "CWD": {
        "id": "CWD",
        "source": "abs",
        "name": "Construction Work Done",
        "description": "Engineering and building construction activity across sectors.",
        "frequency": "Quarterly",
        "category": "housing_construction",
        "aliases": [
            "construction work done",
            "construction activity",
            "building activity",
        ],
        "tags": [
            "engineering construction",
            "residential building",
            "non-residential building",
        ],
    },
    "ITGS": {
        "id": "ITGS",
        "source": "abs",
        "name": "International Trade in Goods and Services",
        "description": "Exports, imports, and trade balance indicators for Australia.",
        "frequency": "Monthly",
        "category": "external_sector",
        "aliases": [
            "international trade",
            "trade balance",
            "exports and imports",
        ],
        "tags": [
            "exports",
            "imports",
            "goods and services trade",
        ],
    },
    "BOP": {
        "id": "BOP",
        "source": "abs",
        "name": "Balance of Payments",
        "description": "Current account, capital account, and financial account aggregates.",
        "frequency": "Quarterly",
        "category": "external_sector",
        "aliases": [
            "balance of payments",
            "current account",
            "external balance",
        ],
        "tags": [
            "financial account",
            "trade in income",
            "net exports",
        ],
    },
    "LI": {
        "id": "LI",
        "source": "abs",
        "name": "Lending Indicators",
        "description": "New lending commitments across housing, personal, and business finance.",
        "frequency": "Monthly",
        "category": "credit_finance",
        "aliases": [
            "lending indicators",
            "new lending",
            "housing finance",
        ],
        "tags": [
            "credit",
            "loan commitments",
            "finance approvals",
        ],
    },
}
