RBA_CATALOGUE = {
    "a2": {
        "id": "a2",
        "source": "rba",
        "name": "Changes in Monetary Policy and Administered Rates",
        "description": "Historical changes in the cash rate target and administered policy rates.",
        "frequency": "Event-driven",
        "category": "monetary_policy",
        "aliases": [
            "cash rate",
            "cash rate target",
            "monetary policy",
            "interest rate decisions",
        ],
        "tags": [
            "rba board",
            "policy moves",
            "target rate",
        ],
    },
    "a3": {
        "id": "a3",
        "source": "rba",
        "name": "Open Market Operations - Current",
        "description": "Current domestic market operations and open market liquidity settings.",
        "frequency": "Daily",
        "category": "monetary_policy",
        "aliases": [
            "open market operations",
            "liquidity operations",
            "domestic market operations",
        ],
        "tags": [
            "omo",
            "liquidity",
            "market operations",
        ],
    },
    "c1": {
        "id": "c1",
        "source": "rba",
        "name": "Credit and Charge Card Statistics",
        "description": "Card transaction values, balances, and credit card activity.",
        "frequency": "Monthly",
        "category": "payments",
        "aliases": [
            "credit card statistics",
            "charge card statistics",
            "card payments",
        ],
        "tags": [
            "payments",
            "cards",
            "merchant spending",
        ],
    },
    "d1": {
        "id": "d1",
        "source": "rba",
        "name": "Growth in Selected Financial Aggregates",
        "description": "Growth rates for money, credit, and selected financial aggregates.",
        "frequency": "Monthly",
        "category": "money_credit",
        "aliases": [
            "financial aggregates growth",
            "credit growth",
            "money growth",
        ],
        "tags": [
            "broad money",
            "financial aggregates",
            "credit conditions",
        ],
    },
    "d2": {
        "id": "d2",
        "source": "rba",
        "name": "Lending and Credit Aggregates",
        "description": "Household and business credit outstanding across major borrower groups.",
        "frequency": "Monthly",
        "category": "money_credit",
        "aliases": [
            "lending and credit aggregates",
            "credit aggregates",
            "credit outstanding",
        ],
        "tags": [
            "housing credit",
            "business credit",
            "household credit",
        ],
    },
    "d3": {
        "id": "d3",
        "source": "rba",
        "name": "Monetary Aggregates",
        "description": "Currency, deposits, and broad money aggregates.",
        "frequency": "Monthly",
        "category": "money_credit",
        "aliases": [
            "monetary aggregates",
            "broad money",
            "money supply",
        ],
        "tags": [
            "m3",
            "currency",
            "deposits",
        ],
    },
    "d5": {
        "id": "d5",
        "source": "rba",
        "name": "Bank Lending Classified by Sector",
        "description": "Bank lending outstanding by borrower sector and loan purpose.",
        "frequency": "Monthly",
        "category": "money_credit",
        "aliases": [
            "bank lending by sector",
            "sectoral bank lending",
            "bank lending",
        ],
        "tags": [
            "credit by sector",
            "business lending",
            "household lending",
        ],
    },
    "f1": {
        "id": "f1",
        "source": "rba",
        "name": "Interest Rates and Yields - Money Market",
        "description": "Short-term money market rates including interbank benchmarks.",
        "frequency": "Daily",
        "category": "interest_rates",
        "aliases": [
            "money market rates",
            "interbank rates",
            "short term interest rates",
        ],
        "tags": [
            "bank bills",
            "overnight rates",
            "money market",
        ],
    },
    "f2": {
        "id": "f2",
        "source": "rba",
        "name": "Capital Market Yields - Government Bonds",
        "description": "Australian Government bond yields across key maturities.",
        "frequency": "Daily",
        "category": "interest_rates",
        "aliases": [
            "government bond yields",
            "bond yields",
            "capital market yields",
        ],
        "tags": [
            "yield curve",
            "sovereign yields",
            "long rates",
        ],
    },
    "f5": {
        "id": "f5",
        "source": "rba",
        "name": "Indicator Lending Rates",
        "description": "Selected lending rates for housing, business, and personal finance.",
        "frequency": "Monthly",
        "category": "interest_rates",
        "aliases": [
            "indicator lending rates",
            "lending rates",
            "loan interest rates",
        ],
        "tags": [
            "business lending rates",
            "housing loan rates",
            "personal loan rates",
        ],
    },
    "f6": {
        "id": "f6",
        "source": "rba",
        "name": "Housing Lending Rates",
        "description": "Owner-occupier and investor mortgage rates across lending products.",
        "frequency": "Monthly",
        "category": "interest_rates",
        "aliases": [
            "housing lending rates",
            "mortgage rates",
            "housing loan rates",
        ],
        "tags": [
            "home loan rates",
            "variable mortgage rates",
            "fixed mortgage rates",
        ],
    },
    "f11": {
        "id": "f11",
        "source": "rba",
        "name": "Exchange Rates",
        "description": "Australian dollar exchange rates against major trading partner currencies.",
        "frequency": "Daily",
        "category": "exchange_rates",
        "aliases": [
            "exchange rates",
            "aud exchange rate",
            "foreign exchange",
        ],
        "tags": [
            "aud",
            "fx",
            "trade weighted index",
        ],
    },
    "g1": {
        "id": "g1",
        "source": "rba",
        "name": "Consumer Price Inflation",
        "description": "CPI, weighted median inflation, and trimmed mean inflation measures.",
        "frequency": "Quarterly",
        "category": "inflation",
        "aliases": [
            "inflation",
            "trimmed mean inflation",
            "core inflation",
            "weighted median inflation",
            "cpi",
        ],
        "tags": [
            "underlying inflation",
            "consumer prices",
            "headline cpi",
        ],
    },
    "g2": {
        "id": "g2",
        "source": "rba",
        "name": "Consumer Price Inflation - Expenditure Groups",
        "description": "Detailed CPI expenditure group contributions and price movements.",
        "frequency": "Quarterly",
        "category": "inflation",
        "aliases": [
            "cpi expenditure groups",
            "detailed cpi",
            "inflation components",
        ],
        "tags": [
            "expenditure classes",
            "cpi components",
            "price contributions",
        ],
    },
    "g3": {
        "id": "g3",
        "source": "rba",
        "name": "Producer Price Indicators",
        "description": "Discontinued producer and import price indicator table.",
        "frequency": "Quarterly",
        "category": "inflation",
        "aliases": [
            "producer price indicators",
            "producer prices",
            "import prices",
        ],
        "tags": [
            "discontinued",
            "upstream prices",
            "price indicators",
        ],
        "discontinued": True,
    },
    "h1": {
        "id": "h1",
        "source": "rba",
        "name": "Gross Domestic Product and Income",
        "description": "Output, expenditure, and income indicators from the national accounts.",
        "frequency": "Quarterly",
        "category": "output_labour",
        "aliases": [
            "gdp",
            "output",
            "income",
            "economic growth",
        ],
        "tags": [
            "national accounts",
            "domestic demand",
            "gdp growth",
        ],
    },
    "h3": {
        "id": "h3",
        "source": "rba",
        "name": "Monthly Activity Indicators",
        "description": "Monthly indicators for consumption, production, and business conditions.",
        "frequency": "Monthly",
        "category": "output_labour",
        "aliases": [
            "monthly activity indicators",
            "activity indicators",
            "monthly activity",
        ],
        "tags": [
            "economic activity",
            "high-frequency activity",
            "monthly indicators",
        ],
    },
    "h5": {
        "id": "h5",
        "source": "rba",
        "name": "Labour Force",
        "description": (
            "Employment, unemployment, and participation indicators from the labour market."
        ),
        "frequency": "Monthly",
        "category": "output_labour",
        "aliases": [
            "labour force",
            "employment",
            "unemployment",
            "unemployment rate",
        ],
        "tags": [
            "jobs",
            "participation",
            "labour market",
        ],
    },
    "i1": {
        "id": "i1",
        "source": "rba",
        "name": "International Trade and Balance of Payments",
        "description": "Trade, current account, and external sector aggregates for Australia.",
        "frequency": "Quarterly",
        "category": "external_sector",
        "aliases": [
            "international trade",
            "balance of payments",
            "current account",
        ],
        "tags": [
            "exports",
            "imports",
            "external balance",
        ],
    },
}
