RBA_CATALOGUE = {
    "a1": {
        "id": "a1",
        "source": "rba",
        "name": "Reserve Bank of Australia Liabilities and Assets - Summary",
        "description": "Summary balance sheet of the Reserve Bank of Australia.",
        "frequency": "Weekly",
        "category": "monetary_policy",
        "aliases": [
            "rba balance sheet",
            "rba assets and liabilities",
            "reserve bank balance sheet",
        ],
        "tags": [
            "balance sheet",
            "central bank assets",
            "liabilities",
        ],
        "frequencies": ["M"],
        "geographies": ["national"],
        "variants": [],
    },
    "a2": {
        "id": "a2",
        "source": "rba",
        "name": "Changes in Monetary Policy and Administered Rates",
        "description": "Historical changes in the cash rate target and administered policy rates.",
        "frequency": "Event-driven",
        "category": "monetary_policy",
        "aliases": [
            "cash rate",
            "cash rate target",
            "monetary policy",
            "interest rate decisions",
        ],
        "tags": [
            "rba board",
            "policy moves",
            "target rate",
        ],
        "frequencies": ["E"],
        "geographies": ["national"],
        "variants": [],
    },
    "a3": {
        "id": "a3",
        "source": "rba",
        "name": "Open Market Operations - Current",
        "description": "Current domestic market operations and open market liquidity settings.",
        "frequency": "Daily",
        "category": "monetary_policy",
        "aliases": [
            "open market operations",
            "liquidity operations",
            "domestic market operations",
        ],
        "tags": [
            "omo",
            "liquidity",
            "market operations",
        ],
        "frequencies": ["D"],
        "geographies": ["national"],
        "variants": [],
    },
    "a5": {
        "id": "a5",
        "source": "rba",
        "name": "Daily Foreign Exchange Market Intervention Transactions",
        "description": (
            "Discontinued daily record of Reserve Bank foreign exchange market "
            "intervention transactions."
        ),
        "frequency": "Daily",
        "category": "exchange_rates",
        "aliases": [
            "foreign exchange market intervention",
            "fx intervention",
            "rba fx intervention",
        ],
        "tags": [
            "discontinued",
            "fx intervention",
            "rba operations",
        ],
        "frequencies": ["D"],
        "geographies": ["national"],
        "variants": [],
        "discontinued": True,
    },
    "c1": {
        "id": "c1",
        "source": "rba",
        "name": "Credit and Charge Card Statistics",
        "description": "Card transaction values, balances, and credit card activity.",
        "frequency": "Monthly",
        "category": "payments",
        "aliases": [
            "credit card statistics",
            "charge card statistics",
            "card payments",
        ],
        "tags": [
            "payments",
            "cards",
            "merchant spending",
        ],
        "frequencies": ["M"],
        "geographies": ["national"],
        "variants": [],
    },
    "c7": {
        "id": "c7",
        "source": "rba",
        "name": "Payments System - Retail Payments",
        "description": "Retail payment system transaction volumes and values across instruments.",
        "frequency": "Monthly",
        "category": "payments",
        "aliases": [
            "retail payments",
            "payments system",
            "payment instruments",
        ],
        "tags": [
            "payments",
            "retail transactions",
            "direct entry",
        ],
        "frequencies": ["M"],
        "geographies": ["national"],
        "variants": [],
    },
    "c9": {
        "id": "c9",
        "source": "rba",
        "name": "ATM Cash Withdrawals",
        "description": "Automated teller machine cash withdrawal volumes and values.",
        "frequency": "Monthly",
        "category": "payments",
        "aliases": [
            "atm withdrawals",
            "cash withdrawals",
            "atm transactions",
        ],
        "tags": [
            "payments",
            "cash usage",
            "atm",
        ],
        "frequencies": ["M"],
        "geographies": ["national"],
        "variants": [],
    },
    "d1": {
        "id": "d1",
        "source": "rba",
        "name": "Growth in Selected Financial Aggregates",
        "description": "Growth rates for money, credit, and selected financial aggregates.",
        "frequency": "Monthly",
        "category": "money_credit",
        "aliases": [
            "financial aggregates growth",
            "credit growth",
            "money growth",
        ],
        "tags": [
            "broad money",
            "financial aggregates",
            "credit conditions",
        ],
        "frequencies": ["M"],
        "geographies": ["national"],
        "variants": [
            {"name": "credit", "aliases": ["credit growth"], "rba_series_ids": None},
            {"name": "money", "aliases": ["money growth", "broad money"], "rba_series_ids": None},
        ],
    },
    "d2": {
        "id": "d2",
        "source": "rba",
        "name": "Lending and Credit Aggregates",
        "description": "Household and business credit outstanding across major borrower groups.",
        "frequency": "Monthly",
        "category": "money_credit",
        "aliases": [
            "lending and credit aggregates",
            "credit aggregates",
            "credit outstanding",
        ],
        "tags": [
            "housing credit",
            "business credit",
            "household credit",
        ],
        "frequencies": ["M"],
        "geographies": ["national"],
        "variants": [
            {"name": "housing", "aliases": ["housing credit"], "rba_series_ids": None},
            {"name": "business", "aliases": ["business credit"], "rba_series_ids": None},
            {"name": "household", "aliases": ["household credit"], "rba_series_ids": None},
        ],
    },
    "d3": {
        "id": "d3",
        "source": "rba",
        "name": "Monetary Aggregates",
        "description": "Currency, deposits, and broad money aggregates.",
        "frequency": "Monthly",
        "category": "money_credit",
        "aliases": [
            "monetary aggregates",
            "broad money",
            "money supply",
        ],
        "tags": [
            "m3",
            "currency",
            "deposits",
        ],
        "frequencies": ["M"],
        "geographies": ["national"],
        "variants": [
            {"name": "currency", "aliases": [], "rba_series_ids": None},
            {"name": "deposits", "aliases": [], "rba_series_ids": None},
            {"name": "broad_money", "aliases": ["m3"], "rba_series_ids": None},
        ],
    },
    "d4": {
        "id": "d4",
        "source": "rba",
        "name": "Bank Lending to Business - Total Credit Outstanding by Size and Sector",
        "description": "Bank business lending broken down by borrower size and industry.",
        "frequency": "Monthly",
        "category": "money_credit",
        "aliases": [
            "business lending by size",
            "business credit by sector",
            "business lending industry",
        ],
        "tags": [
            "business credit",
            "sme lending",
            "industry lending",
        ],
        "frequencies": ["M"],
        "geographies": ["national"],
        "variants": [
            {"name": "small_business", "aliases": ["sme"], "rba_series_ids": None},
            {"name": "large_business", "aliases": [], "rba_series_ids": None},
        ],
    },
    "d5": {
        "id": "d5",
        "source": "rba",
        "name": "Bank Lending Classified by Sector",
        "description": "Bank lending outstanding by borrower sector and loan purpose.",
        "frequency": "Monthly",
        "category": "money_credit",
        "aliases": [
            "bank lending by sector",
            "sectoral bank lending",
            "bank lending",
        ],
        "tags": [
            "credit by sector",
            "business lending",
            "household lending",
        ],
        "frequencies": ["M"],
        "geographies": ["national"],
        "variants": [
            {"name": "business", "aliases": ["business lending"], "rba_series_ids": None},
            {"name": "household", "aliases": ["household lending"], "rba_series_ids": None},
        ],
    },
    "d14": {
        "id": "d14",
        "source": "rba",
        "name": "Growth in Selected Financial Aggregates - Consolidated",
        "description": "Long-run consolidated growth rates for credit and financial aggregates.",
        "frequency": "Monthly",
        "category": "money_credit",
        "aliases": [
            "consolidated financial aggregates",
            "long run credit growth",
            "financial aggregates historical",
        ],
        "tags": [
            "credit history",
            "broad money history",
            "long run series",
        ],
        "frequencies": ["M"],
        "geographies": ["national"],
        "variants": [],
    },
    "e1": {
        "id": "e1",
        "source": "rba",
        "name": "Household and Business Balance Sheets",
        "description": "Household and business balance sheet aggregates including debt and assets.",
        "frequency": "Quarterly",
        "category": "household_finance",
        "aliases": [
            "household balance sheet",
            "business balance sheet",
            "household debt",
        ],
        "tags": [
            "household wealth",
            "household debt",
            "business balance sheet",
        ],
        "frequencies": ["Q"],
        "geographies": ["national"],
        "variants": [
            {"name": "household", "aliases": ["household debt"], "rba_series_ids": None},
            {"name": "business", "aliases": [], "rba_series_ids": None},
        ],
    },
    "e2": {
        "id": "e2",
        "source": "rba",
        "name": "Selected Household Ratios",
        "description": (
            "Household debt-to-income, assets-to-income, and related wealth indicators."
        ),
        "frequency": "Quarterly",
        "category": "household_finance",
        "aliases": [
            "household ratios",
            "household debt to income",
            "household wealth ratios",
        ],
        "tags": [
            "debt service",
            "household income",
            "household wealth",
        ],
        "frequencies": ["Q"],
        "geographies": ["national"],
        "variants": [],
    },
    "e13": {
        "id": "e13",
        "source": "rba",
        "name": "Household Non-Financial Assets",
        "description": "Household holdings of non-financial assets, primarily housing.",
        "frequency": "Quarterly",
        "category": "household_finance",
        "aliases": [
            "household non-financial assets",
            "housing assets",
            "household dwelling wealth",
        ],
        "tags": [
            "housing wealth",
            "dwelling stock",
            "household assets",
        ],
        "frequencies": ["Q"],
        "geographies": ["national"],
        "variants": [],
    },
    "f1": {
        "id": "f1",
        "source": "rba",
        "name": "Interest Rates and Yields - Money Market",
        "description": "Short-term money market rates including interbank benchmarks.",
        "frequency": "Daily",
        "category": "interest_rates",
        "aliases": [
            "money market rates",
            "interbank rates",
            "short term interest rates",
        ],
        "tags": [
            "bank bills",
            "overnight rates",
            "money market",
        ],
        "frequencies": ["D"],
        "geographies": ["national"],
        "variants": [
            {"name": "bank_bills", "aliases": ["bank bill"], "rba_series_ids": None},
            {
                "name": "overnight",
                "aliases": ["overnight rates", "overnight indexed swap"],
                "rba_series_ids": None,
            },
        ],
    },
    "f2": {
        "id": "f2",
        "source": "rba",
        "name": "Capital Market Yields - Government Bonds",
        "description": "Australian Government bond yields across key maturities.",
        "frequency": "Daily",
        "category": "interest_rates",
        "aliases": [
            "government bond yields",
            "bond yields",
            "capital market yields",
        ],
        "tags": [
            "yield curve",
            "sovereign yields",
            "long rates",
        ],
        "frequencies": ["D"],
        "geographies": ["national"],
        "variants": [],
    },
    "f3": {
        "id": "f3",
        "source": "rba",
        "name": "Capital Market Yields and Spreads - Non-Government Instruments",
        "description": "Non-government capital market yields and spreads over Australian bonds.",
        "frequency": "Daily",
        "category": "interest_rates",
        "aliases": [
            "non-government yields",
            "credit spreads",
            "corporate bond spreads",
        ],
        "tags": [
            "credit spreads",
            "corporate yields",
            "swap spreads",
        ],
        "frequencies": ["D"],
        "geographies": ["national"],
        "variants": [],
    },
    "f4": {
        "id": "f4",
        "source": "rba",
        "name": "Australian Share Market",
        "description": "Equity index levels, price-earnings ratios, and dividend yields.",
        "frequency": "Daily",
        "category": "interest_rates",
        "aliases": [
            "share market",
            "equity market",
            "asx",
        ],
        "tags": [
            "equities",
            "share prices",
            "dividend yield",
        ],
        "frequencies": ["D"],
        "geographies": ["national"],
        "variants": [],
    },
    "f5": {
        "id": "f5",
        "source": "rba",
        "name": "Indicator Lending Rates",
        "description": "Selected lending rates for housing, business, and personal finance.",
        "frequency": "Monthly",
        "category": "interest_rates",
        "aliases": [
            "indicator lending rates",
            "lending rates",
            "loan interest rates",
        ],
        "tags": [
            "business lending rates",
            "housing loan rates",
            "personal loan rates",
        ],
        "frequencies": ["M"],
        "geographies": ["national"],
        "variants": [
            {"name": "business", "aliases": ["business lending rates"], "rba_series_ids": None},
            {"name": "housing", "aliases": ["housing loan rates"], "rba_series_ids": None},
            {"name": "personal", "aliases": ["personal loan rates"], "rba_series_ids": None},
        ],
    },
    "f6": {
        "id": "f6",
        "source": "rba",
        "name": "Housing Lending Rates",
        "description": "Owner-occupier and investor mortgage rates across lending products.",
        "frequency": "Monthly",
        "category": "interest_rates",
        "aliases": [
            "housing lending rates",
            "mortgage rates",
            "housing loan rates",
        ],
        "tags": [
            "home loan rates",
            "variable mortgage rates",
            "fixed mortgage rates",
        ],
        "frequencies": ["M"],
        "geographies": ["national"],
        "variants": [
            {"name": "owner_occupier", "aliases": ["owner-occupier"], "rba_series_ids": None},
            {"name": "investor", "aliases": ["investment"], "rba_series_ids": None},
        ],
    },
    "f7": {
        "id": "f7",
        "source": "rba",
        "name": "Business Finance Lending Rates",
        "description": "Average interest rates on new and outstanding business loans.",
        "frequency": "Monthly",
        "category": "interest_rates",
        "aliases": [
            "business lending rates",
            "business loan rates",
            "corporate loan rates",
        ],
        "tags": [
            "business loans",
            "small business rates",
            "large business rates",
        ],
        "frequencies": ["M"],
        "geographies": ["national"],
        "variants": [
            {"name": "small_business", "aliases": ["sme rates"], "rba_series_ids": None},
            {"name": "large_business", "aliases": [], "rba_series_ids": None},
        ],
    },
    "f8": {
        "id": "f8",
        "source": "rba",
        "name": "Retail Deposit and Investment Rates",
        "description": "Retail deposit, term deposit, and cash management rates.",
        "frequency": "Monthly",
        "category": "interest_rates",
        "aliases": [
            "deposit rates",
            "term deposit rates",
            "savings rates",
        ],
        "tags": [
            "retail deposits",
            "term deposits",
            "savings accounts",
        ],
        "frequencies": ["M"],
        "geographies": ["national"],
        "variants": [
            {"name": "term_deposit", "aliases": ["term deposit rates"], "rba_series_ids": None},
            {"name": "at_call", "aliases": ["savings"], "rba_series_ids": None},
        ],
    },
    "f11": {
        "id": "f11",
        "source": "rba",
        "name": "Exchange Rates",
        "description": "Australian dollar exchange rates against major trading partner currencies.",
        "frequency": "Daily",
        "category": "exchange_rates",
        "aliases": [
            "exchange rates",
            "aud exchange rate",
            "foreign exchange",
        ],
        "tags": [
            "aud",
            "fx",
            "trade weighted index",
        ],
        "frequencies": ["D"],
        "geographies": ["national"],
        "variants": [],
    },
    "f12": {
        "id": "f12",
        "source": "rba",
        "name": "Exchange Rates - Monthly Average",
        "description": (
            "Monthly average exchange rates against major currencies and trade-weighted index."
        ),
        "frequency": "Monthly",
        "category": "exchange_rates",
        "aliases": [
            "monthly exchange rates",
            "monthly fx",
            "average exchange rate",
        ],
        "tags": [
            "aud average",
            "trade weighted index",
            "monthly fx",
        ],
        "frequencies": ["M"],
        "geographies": ["national"],
        "variants": [],
    },
    "f15": {
        "id": "f15",
        "source": "rba",
        "name": "Real Exchange Rate Measures",
        "description": "Real and real trade-weighted exchange rate measures.",
        "frequency": "Monthly",
        "category": "exchange_rates",
        "aliases": [
            "real exchange rate",
            "real twi",
            "real trade weighted index",
        ],
        "tags": [
            "real exchange rate",
            "competitiveness",
            "twi",
        ],
        "frequencies": ["M"],
        "geographies": ["national"],
        "variants": [],
    },
    "g1": {
        "id": "g1",
        "source": "rba",
        "name": "Consumer Price Inflation",
        "description": "CPI, weighted median inflation, and trimmed mean inflation measures.",
        "frequency": "Quarterly",
        "category": "inflation",
        "aliases": [
            "inflation",
            "trimmed mean inflation",
            "core inflation",
            "weighted median inflation",
            "cpi",
        ],
        "tags": [
            "underlying inflation",
            "consumer prices",
            "headline cpi",
        ],
        "frequencies": ["Q"],
        "geographies": ["national"],
        "variants": [
            {"name": "headline", "aliases": ["headline cpi", "cpi"], "rba_series_ids": None},
            {
                "name": "trimmed_mean",
                "aliases": ["core", "trimmed mean inflation"],
                "rba_series_ids": None,
            },
            {
                "name": "weighted_median",
                "aliases": ["weighted median inflation"],
                "rba_series_ids": None,
            },
        ],
    },
    "g2": {
        "id": "g2",
        "source": "rba",
        "name": "Consumer Price Inflation - Expenditure Groups",
        "description": "Detailed CPI expenditure group contributions and price movements.",
        "frequency": "Quarterly",
        "category": "inflation",
        "aliases": [
            "cpi expenditure groups",
            "detailed cpi",
            "inflation components",
        ],
        "tags": [
            "expenditure classes",
            "cpi components",
            "price contributions",
        ],
        "frequencies": ["Q"],
        "geographies": ["national"],
        "variants": [],
    },
    "g3": {
        "id": "g3",
        "source": "rba",
        "name": "Inflation Expectations",
        "description": (
            "Consumer, union, market, and business measures of expected inflation."
        ),
        "frequency": "Monthly",
        "category": "inflation",
        "aliases": [
            "inflation expectations",
            "expected inflation",
            "consumer inflation expectations",
        ],
        "tags": [
            "inflation expectations",
            "consumer expectations",
            "market inflation expectations",
        ],
        "frequencies": ["M", "Q"],
        "geographies": ["national"],
        "variants": [
            {"name": "consumer", "aliases": ["consumer expectations"], "rba_series_ids": None},
            {"name": "market", "aliases": ["market expectations"], "rba_series_ids": None},
            {"name": "union", "aliases": [], "rba_series_ids": None},
        ],
    },
    "g4": {
        "id": "g4",
        "source": "rba",
        "name": "Measures of Consumer Price Inflation",
        "description": "Alternative and supplementary measures of consumer price inflation.",
        "frequency": "Quarterly",
        "category": "inflation",
        "aliases": [
            "alternative inflation measures",
            "underlying inflation measures",
            "supplementary inflation",
        ],
        "tags": [
            "underlying inflation",
            "inflation measures",
            "supplementary cpi",
        ],
        "frequencies": ["Q"],
        "geographies": ["national"],
        "variants": [],
    },
    "h1": {
        "id": "h1",
        "source": "rba",
        "name": "Gross Domestic Product and Income",
        "description": "Output, expenditure, and income indicators from the national accounts.",
        "frequency": "Quarterly",
        "category": "output_labour",
        "aliases": [
            "gdp",
            "output",
            "income",
            "economic growth",
        ],
        "tags": [
            "national accounts",
            "domestic demand",
            "gdp growth",
        ],
        "frequencies": ["Q"],
        "geographies": ["national"],
        "variants": [
            {"name": "gdp", "aliases": ["output", "economic growth"], "rba_series_ids": None},
            {"name": "income", "aliases": [], "rba_series_ids": None},
        ],
    },
    "h2": {
        "id": "h2",
        "source": "rba",
        "name": "Household Finances - Selected Ratios",
        "description": (
            "Household income, saving, and consumption ratios from the national accounts."
        ),
        "frequency": "Quarterly",
        "category": "output_labour",
        "aliases": [
            "household saving ratio",
            "household consumption",
            "household finances",
        ],
        "tags": [
            "saving ratio",
            "household consumption",
            "disposable income",
        ],
        "frequencies": ["Q"],
        "geographies": ["national"],
        "variants": [],
    },
    "h3": {
        "id": "h3",
        "source": "rba",
        "name": "Monthly Activity Indicators",
        "description": "Monthly indicators for consumption, production, and business conditions.",
        "frequency": "Monthly",
        "category": "output_labour",
        "aliases": [
            "monthly activity indicators",
            "activity indicators",
            "monthly activity",
        ],
        "tags": [
            "economic activity",
            "high-frequency activity",
            "monthly indicators",
        ],
        "frequencies": ["M"],
        "geographies": ["national"],
        "variants": [],
    },
    "h4": {
        "id": "h4",
        "source": "rba",
        "name": "Business Sector Finances",
        "description": "Business sector profits, investment, and finance indicators.",
        "frequency": "Quarterly",
        "category": "output_labour",
        "aliases": [
            "business profits",
            "business investment",
            "business sector finances",
        ],
        "tags": [
            "company profits",
            "business investment",
            "business finance",
        ],
        "frequencies": ["Q"],
        "geographies": ["national"],
        "variants": [],
    },
    "h5": {
        "id": "h5",
        "source": "rba",
        "name": "Labour Force",
        "description": (
            "Employment, unemployment, and participation indicators from the labour market."
        ),
        "frequency": "Monthly",
        "category": "output_labour",
        "aliases": [
            "labour force",
            "employment",
            "unemployment",
            "unemployment rate",
        ],
        "tags": [
            "jobs",
            "participation",
            "labour market",
        ],
        "frequencies": ["M"],
        "geographies": ["national"],
        "variants": [
            {"name": "employment", "aliases": ["employed persons"], "rba_series_ids": None},
            {
                "name": "unemployment_rate",
                "aliases": ["unemployment"],
                "rba_series_ids": None,
            },
            {
                "name": "participation_rate",
                "aliases": ["participation"],
                "rba_series_ids": None,
            },
        ],
    },
    "i1": {
        "id": "i1",
        "source": "rba",
        "name": "International Trade and Balance of Payments",
        "description": "Trade, current account, and external sector aggregates for Australia.",
        "frequency": "Quarterly",
        "category": "external_sector",
        "aliases": [
            "international trade",
            "balance of payments",
            "current account",
        ],
        "tags": [
            "exports",
            "imports",
            "external balance",
        ],
        "frequencies": ["Q"],
        "geographies": ["national"],
        "variants": [
            {"name": "trade", "aliases": ["international trade"], "rba_series_ids": None},
            {"name": "current_account", "aliases": [], "rba_series_ids": None},
        ],
    },
    "i2": {
        "id": "i2",
        "source": "rba",
        "name": "Australia's Foreign Assets and Liabilities",
        "description": (
            "International investment position and stocks of foreign assets and liabilities."
        ),
        "frequency": "Quarterly",
        "category": "external_sector",
        "aliases": [
            "international investment position",
            "foreign assets and liabilities",
            "iip",
        ],
        "tags": [
            "foreign assets",
            "foreign liabilities",
            "net international investment",
        ],
        "frequencies": ["Q"],
        "geographies": ["national"],
        "variants": [],
    },
    "i3": {
        "id": "i3",
        "source": "rba",
        "name": "Australian Exports - Values",
        "description": "Value of Australian exports by category.",
        "frequency": "Monthly",
        "category": "external_sector",
        "aliases": [
            "australian exports",
            "export values",
            "exports by category",
        ],
        "tags": [
            "exports",
            "commodity exports",
            "trade",
        ],
        "frequencies": ["M"],
        "geographies": ["national"],
        "variants": [],
    },
    "i4": {
        "id": "i4",
        "source": "rba",
        "name": "Australian Imports - Values",
        "description": "Value of Australian imports by category.",
        "frequency": "Monthly",
        "category": "external_sector",
        "aliases": [
            "australian imports",
            "import values",
            "imports by category",
        ],
        "tags": [
            "imports",
            "trade",
            "import values",
        ],
        "frequencies": ["M"],
        "geographies": ["national"],
        "variants": [],
    },
}
